name: Flutter Build app

on: 
  push:
    tags:
      - "v*.*.*"

env:
  APP_NAME: "JalDrishti"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/jal_dristi_app/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: app/jal_dristi_app/build/app/outputs/apk/release/app-release.apk